import Link from "next/link";
export const metadata = {
  title: "Resend practice with Next.js",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="mt-4 flex flex-col gap-2 text-center">
      <Link className="underline" href='/react-form/state-form'>React State Form practice</Link >
      <Link className="underline" href='/react-form/ref-form'>React Ref Form practice</Link >
      <Link className="underline" href='/immer'>Immer practice</Link >
      <Link className="underline" href='/to-do'>React TodoList practice</Link >
      <Link className="underline" href='/react-hook-form'>react-hook-form practice</Link >
    </main>
  );
}
